ALTER TABLE "assets" ADD COLUMN IF NOT EXISTS "source_ticker" text;--> statement-breakpoint
UPDATE "assets"
SET "source_ticker" = CASE "ticker"
  WHEN 'BOVA11' THEN 'BOVA11.SA'
  WHEN 'SPXI11' THEN 'SPXI11.SA'
  WHEN 'IMAB11' THEN 'IMAB11.SA'
  WHEN 'SMAL11' THEN 'SMAL11.SA'
  WHEN 'CDB_POS' THEN 'CDI'
  WHEN 'TESOURO_SELIC' THEN 'SELIC'
  WHEN 'BTC' THEN 'BTC-USD'
  WHEN 'ETH' THEN 'ETH-USD'
  WHEN 'OURO' THEN 'GC=F'
  ELSE NULL
END;
